    CREATE DATABASE MegaSoft;
    USE MegaSoft;
    CREATE TABLE client (
    ID int NOT NULL,
    NAME VARCHAR(1000)
    PRIMARY KEY(ID),
    CHECK (LENGTH(NAME)>1 AND LENGTH(NAME)<=1000));
    CREATE TABLE worker (
    ID int NOT NULL,
    NAME VARCHAR(1000),
    BIRTHDAY DATE,
    LEVEL VARCHAR(10) NOT NULL,
    SALARY int,
    PRIMARY KEY(ID),
    CHECK(BIRTHDAY.YEAR>1900 AND LENGTH(NAME)>1 AND LENGTH(NAME)<=1000 AND SALARY>=100 AND SALARY<=100000 AND LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')));
    CREATE TABLE project (
    ID INT NOT NULL PRIMARY KEY,
    CLIENT_ID INT FOREIGN KEY REFERENCES client(ID),
    START_DATE DATE,
    FINISH_DATE DATE);
    CREATE TABLE project_worker(
    PROJECT_ID INT FOREIGN KEY REFERENCES project(ID),
    WORKER_ID INT FOREIGN KEY REFERENCES worker(ID),
    PRIMARY KEY(PROJECT_ID, WORKER_ID));